const friendsEntries = [
  {
    entryid: 1,
    userid: 2,
    datetime: "2023-08-03 08:30:00",
    mood: 3,
    activities: ["reading", "workout"],
    note: "Had a productive morning.",
    photo: "entry_1.jpg",
    voicememo: "entry_1.mp3",
  },
  {
    entryid: 2,
    userid: 4,
    datetime: "2023-08-03 12:45:00",
    mood: 1,
    activities: ["workout"],
    note: "Feeling a bit tired today.",
    photo: "entry_2.jpg",
    voicememo: "entry_2.mp3",
  },
  {
    entryid: 3,
    userid: 3,
    datetime: "2023-08-03 15:20:00",
    mood: 2,
    activities: ["reading"],
    note: "Enjoyed the book I was reading.",
    photo: "entry_3.jpg",
    voicememo: "entry_3.mp3",
  },
  {
    entryid: 4,
    userid: 1,
    datetime: "2023-08-03 18:00:00",
    mood: 4,
    activities: ["workout"],
    note: "Had a great workout session.",
    photo: "entry_4.jpg",
    voicememo: "entry_4.mp3",
  },
  {
    entryid: 5,
    userid: 5,
    datetime: "2023-08-03 20:10:00",
    mood: 0,
    activities: ["reading"],
    note: "Feeling a bit down today.",
    photo: "entry_5.jpg",
    voicememo: "entry_5.mp3",
  },
  {
    entryid: 6,
    userid: 3,
    datetime: "2023-08-04 09:15:00",
    mood: 3,
    activities: ["reading", "workout"],
    note: "Had a productive morning.",
    photo: "entry_6.jpg",
    voicememo: "entry_6.mp3",
  },
  {
    entryid: 7,
    userid: 2,
    datetime: "2023-08-04 12:30:00",
    mood: 2,
    activities: ["workout"],
    note: "Feeling energetic after the workout.",
    photo: "entry_7.jpg",
    voicememo: "entry_7.mp3",
  },
  {
    entryid: 8,
    userid: 4,
    datetime: "2023-08-04 16:00:00",
    mood: 1,
    activities: ["reading"],
    note: "Didn't have much time to read.",
    photo: "entry_8.jpg",
    voicememo: "entry_8.mp3",
  },
  {
    entryid: 9,
    userid: 1,
    datetime: "2023-08-04 19:20:00",
    mood: 0,
    activities: ["workout"],
    note: "Feeling a bit lazy today.",
    photo: "entry_9.jpg",
    voicememo: "entry_9.mp3",
  },
  {
    entryid: 10,
    userid: 5,
    datetime: "2023-08-04 21:40:00",
    mood: 4,
    activities: ["reading"],
    note: "Couldn't put the book down.",
    photo: "entry_10.jpg",
    voicememo: "entry_10.mp3",
  },
  {
    entryid: 11,
    userid: 2,
    datetime: "2023-08-05 08:00:00",
    mood: 3,
    activities: ["reading", "workout"],
    note: "Feeling motivated today.",
    photo: "entry_11.jpg",
    voicememo: "entry_11.mp3",
  },
  {
    entryid: 12,
    userid: 4,
    datetime: "2023-08-05 12:15:00",
    mood: 2,
    activities: ["workout"],
    note: "Struggling to focus during the workout.",
    photo: "entry_12.jpg",
    voicememo: "entry_12.mp3",
  },
  {
    entryid: 13,
    userid: 3,
    datetime: "2023-08-05 15:30:00",
    mood: 1,
    activities: ["reading"],
    note: "The book is getting interesting.",
    photo: "entry_13.jpg",
    voicememo: "entry_13.mp3",
  },
  {
    entryid: 14,
    userid: 1,
    datetime: "2023-08-05 18:45:00",
    mood: 0,
    activities: ["workout"],
    note: "Feeling accomplished after the workout.",
    photo: "entry_14.jpg",
    voicememo: "entry_14.mp3",
  },
  {
    entryid: 15,
    userid: 5,
    datetime: "2023-08-05 21:00:00",
    mood: 4,
    activities: ["reading"],
    note: "Finished the book - What a journey!",
    photo: "entry_15.jpg",
    voicememo: "entry_15.mp3",
  },
];

module.exports = friendsEntries;
